trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build_push
    displayName: 'Docker Stage'
    jobs:
      - job: 'Build_push'
        displayName: 'Build and Push'
        steps:
          - task: Docker@2
            displayName: 'Build and Push Docker image'
            inputs:
              containerRegistry: 'docker-hub-lucasnebot'
              repository: 'lucasnebot/project1'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: 'latest'

